[package]
authors = ["CarlosEduardoL"]
name = "r8"
version = "0.1.0"
edition = "2021"
description = "Simple Chip8 emulator"

[dependencies]
env_logger = "0.10"
log = "0.4"
egui = { version = "0.22.0", optional = true }
rfd = { version = "0.12.0", optional = true }

[target.'cfg(unix)'.dependencies]
sdl2 = { version = "0.35.2", optional = true }
egui_sdl2_gl = { version = "0.22.1", optional = true }

[target.'cfg(windows)'.dependencies]
sdl2 = { version = "0.35.2", features = ["bundled"], optional = true }
egui_sdl2_gl = { version = "0.22.1", features = ["sdl2_bundled"], optional = true }

[features]
sdl2-gui = ["sdl2", "egui_sdl2_gl", "egui", "rfd"]

[lib]
name = "r8"
path = "src/emulator/lib.rs"

[[bin]]
name = "r8-sdl2"
path = "src/sdl2-gui/main.rs"
required-features = ["sdl2-gui"]

# [profile.release]
# lto = true
